### ISSUE TITLE
Front page needs to have something covering recent news.

### ISSUE THREAD

**Issue by jcfrosty** [Sabayon/w0h000#4]
I hear, on avg more than 40% of people who visit websites never get past the home page. I've found this personally to be true on a small church website I build and design. We should have something that gives a small synopsis of the last blog or an article that we deem important knowledge for our users to know. Hook them in and have them click to read the full article.

**Comment by Ryuno-Ki** [comment]
@jcfrosty, @mudler Could you close this ticket? I have no permissions to do so. The other repo is the correct place.

**Comment by jcfrosty** [comment]
Closed :D
